// SPDX-License-Identifier: LicenseRef-1Cat-Community-1.0
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from "recharts";
import { ArrowDownToLine, ArrowUpFromLine, Database } from "lucide-react";
import { Button } from "@/onecat/ui";
import { useQuery } from "./api";
import { ErrorNotice, useText } from "./common";
import { modelLabel } from "./model-label";

type Usage = {
  days: number;
  since: number;
  until: number;
  requests: number;
  input_tokens: number | null;
  output_tokens: number | null;
  cached_tokens: number | null;
  input_measured: number;
  output_measured: number;
  cache_measured: number;
  model?: string;
  source?: string;
  successful_requests: number;
  cancelled_requests: number;
  active: number;
  models: { id: string; name: string }[];
  timeline: { at: number; input_tokens: number | null; output_tokens: number | null; cached_tokens: number | null }[];
};

export function TokenUsage({ days = 1, onDaysChange, model = "", onModelChange, source = "", onSourceChange }: {
  days?: number; onDaysChange?: (value: number) => void;
  model?: string; onModelChange?: (value: string) => void;
  source?: string; onSourceChange?: (value: string) => void;
}) {
  const t = useText();
  const query = useQuery<Usage>(`/api/requests/usage?days=${days}&model=${encodeURIComponent(model)}&source=${source}`, 5000);
  const data = query.data?.days === days && (query.data.model || "") === model && (query.data.source || "") === source ? query.data : undefined;
  const count = (n: number | null | undefined) =>
    n == null ? "—" : n.toLocaleString();
  const cards = [
    {
      id: "input",
      label: t("输入 tokens", "Input tokens"),
      subtitle: t("输入总量", "Total input"),
      icon: ArrowDownToLine,
      value: data?.input_tokens,
      measured: data?.input_measured,
      description: t(
        "包含前缀缓存命中的输入",
        "Includes inputs served from prefix cache",
      ),
    },
    {
      id: "output",
      label: t("输出 tokens", "Output tokens"),
      subtitle: "Decode",
      icon: ArrowUpFromLine,
      value: data?.output_tokens,
      measured: data?.output_measured,
      description: t(
        "模型实际生成的输出",
        "Output actually generated by the model",
      ),
    },
    {
      id: "cache",
      label: t("缓存命中 tokens", "Cache-hit tokens"),
      subtitle: "Prefix cache",
      icon: Database,
      value: data?.cached_tokens,
      measured: data?.cache_measured,
      description: t(
        "属于输入的一部分，不重复相加",
        "A subset of input; not counted twice",
      ),
    },
  ];
  return (
    <section className="oc-panel oc-token-usage">
      <div className="oc-row oc-usage-heading">
        <div>
          <h2>
            {t("这台机器处理了多少 tokens", "Tokens processed by this machine")}
          </h2>
          <p className="oc-muted">
            {data
              ? t(
                  `近 ${days} 天 · ${count(data.requests)} 次已结束请求`,
                  `Last ${days} ${days === 1 ? "day" : "days"} · ${count(data.requests)} finished requests`,
                )
              : t("正在读取统计…", "Loading usage…")}
          </p>
        </div>
        <div
          className="oc-usage-periods"
          role="group"
          aria-label={t("统计时间范围", "Usage period")}
        >
          {[1, 3, 7].map((day) => (
            <Button
              key={day}
              size="sm"
              variant={day === days ? "secondary" : "ghost"}
              aria-pressed={day === days}
              onClick={() => onDaysChange?.(day)}
            >
              {t(`近 ${day} 天`, `${day} ${day === 1 ? "day" : "days"}`)}
            </Button>
          ))}
        </div>
      </div>
      <div className="oc-usage-filters">
        <select aria-label={t("统计模型", "Usage model")} value={model} onChange={event => onModelChange?.(event.target.value)}>
          <option value="">{t("所有模型", "All models")}</option>
          {model && !query.data?.models?.some(item => item.id === model) && <option value={model}>{modelLabel(model)}</option>}
          {query.data?.models?.map(item => <option key={item.id} value={item.id}>{modelLabel(item.name)}</option>)}
        </select>
        <select aria-label={t("请求来源", "Request source")} value={source} onChange={event => onSourceChange?.(event.target.value)}>
          <option value="">{t("聊天与 API", "Chat and API")}</option><option value="studio">{t("聊天", "Chat")}</option><option value="api">API</option>
        </select>
        <span className="oc-muted">{t("进行中（含排队）", "In flight (including queued)")}: {data?.active ?? "—"}</span>
        <span className="oc-muted" title={t("取消请求不计入成功率", "Cancelled requests are excluded")}>
          {t("成功率", "Success rate")}: {data && data.requests > data.cancelled_requests
            ? (100 * data.successful_requests / (data.requests - data.cancelled_requests)).toFixed(1) + "%" : "—"}
        </span>
      </div>
      <ErrorNotice error={query.error} />
      <div className="oc-token-cards">
        {cards.map((card) => (
          <div className="oc-token-card" data-usage={card.id} key={card.id}>
            <div className="oc-token-label">
              <card.icon size={17} />
              <span>{card.label}</span>
              <small>{card.subtitle}</small>
            </div>
            <strong title={count(card.value)}>{count(card.value)}</strong>
            <p>{card.description}</p>
          </div>
        ))}
      </div>
      {data && cards.some(card => card.measured != null && card.measured < data.requests) && <details className="oc-usage-coverage">
        <summary>{t("部分请求缺少统计，当前显示已采集数据", "Some requests have incomplete metrics; measured values are shown")}</summary>
        {cards.map(card => <p key={card.id}>{card.label} · {t(`已采集 ${card.measured} / ${data.requests} 次`, `${card.measured} / ${data.requests} measured`)}</p>)}
      </details>}
      {!!data?.requests && !!data?.timeline?.length && <div className="oc-usage-trend">
        <h3>{t("Token 产出趋势", "Token usage over time")}</h3>
        <ResponsiveContainer width="100%" height={190}>
          <LineChart data={data.timeline} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}>
            <CartesianGrid vertical={false} stroke="var(--border)" />
            <XAxis dataKey="at" minTickGap={60} tick={{ fontSize: 12 }} tickFormatter={value => new Date(value * 1000).toLocaleString(t("zh-CN", "en-US"), days === 7 ? { month: "short", day: "numeric" } : { hour: "2-digit", minute: "2-digit", hour12: false })} />
            <YAxis width={54} tick={{ fontSize: 12 }} tickFormatter={value => value >= 1000 ? `${(value / 1000).toFixed(0)}k` : String(value)} />
            <Tooltip labelFormatter={value => new Date(Number(value) * 1000).toLocaleString(t("zh-CN", "en-US"))} contentStyle={{ background: "var(--popover)", border: "1px solid var(--border)", borderRadius: 10 }} />
            <Legend />
            <Line dataKey="input_tokens" name={t("输入", "Input")} stroke="var(--oc-input-color)" dot={false} isAnimationActive={false} />
            <Line dataKey="output_tokens" name={t("输出", "Output")} stroke="var(--primary)" dot={false} strokeWidth={2} isAnimationActive={false} />
            <Line dataKey="cached_tokens" name={t("缓存命中（输入子集）", "Cache hits (subset of input)")} stroke="var(--oc-cache-color)" dot={false} strokeDasharray="4 3" isAnimationActive={false} />
          </LineChart>
        </ResponsiveContainer>
      </div>}
      {data?.requests === 0 && <p className="oc-muted oc-spaced">{t("当前筛选范围内还没有请求。完成聊天或 API 调用后，这里会显示产出趋势。", "No requests in this range yet. Chat or make an API call to see usage trends.")}</p>}
      <p className="oc-muted oc-chart-caption">
        {t(
          "统计经 Studio 的聊天和 API 请求，按请求开始时间滚动累计，每 5 秒更新。使用模型服务返回的实际 token 数；缺失数据不估算。",
          "Rolling totals for chat and API requests through Studio, grouped by request start time and refreshed every 5 s. Counts are reported by the model service; missing values are not estimated.",
        )}
      </p>
    </section>
  );
}
